server:
    port: 8075

# API Gateway routes configuration
spring:
  cloud:
    gateway:
      routes:
        - id: guest-service
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/api/guests/**
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/reservations/**
        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/api/rooms/**

eureka:
  instance:
    hostname: localhost

