server:
    port: 8075

# API Gateway routes configuration
spring:
  cloud:
    gateway:
      routes:
        - id: guest-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/guests/**
        - id: reservation-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/reservations/**
        - id: room-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/rooms/**

eureka:
  instance:
    hostname: localhost

