server:
    port: 8075

# API Gateway routes configuration
spring:
  cloud:
    gateway:
      routes:
        - id: guest-service
          uri: lb://guest-service
          predicates:
            - Path=/api/guests/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/api/rooms/**

