server:
    port: 8075

spring:
  cloud:
    gateway:
      routes:
        - id: guest-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/guests/**
        - id: reservation-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/reservations/**
        - id: room-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/rooms/**
