server:
    port: 8989

# API Gateway routes configuration
spring:
  cloud:
    gateway:
      routes:
        - id: GUEST-SERVICE
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/api/guests/**
        - id: RESERVATION-SERVICE
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/reservations/**
        - id: ROOM-SERVICE
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/api/rooms/**

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

