server:
    port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/guest_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
        
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints
  tracing:
    sample-rate: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka