server:
    port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints

# Configuration for Feign clients
feign:
  client:
    config:
      default:
        connectTimeout: 5000  # Connection timeout in milliseconds
        readTimeout: 5000     # Read timeout in milliseconds

# URLs for guest and room services
guest-service:
  url: http://localhost:8081  # Placeholder URL for guest service

room-service:
  url: http://localhost:8083  # Placeholder URL for room service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost