server:
    port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/room_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate:
        ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints
